name: goreleaser

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  goreleaser:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.21
      
      - name: Format
        working-directory: friendly-captcha-sdk-testserver
        run: if [ "$(gofmt -s -l . | wc -l)" -gt 0 ]; then exit 1; fi
  
      - name: vet
        working-directory: friendly-captcha-sdk-testserver
        run: if [ "$(go vet ./... | wc -l)" -gt 0 ]; then exit 1; fi
    
      - name: GoReleaser
        uses: goreleaser/goreleaser-action@v2
        with:
          workdir: friendly-captcha-sdk-testserver
          distribution: goreleaser
          version: latest
          args: release --clean
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
